### ISSUE TITLE
P1, P2 and LBG colors in older levels aren't loaded properly

### ISSUE THREAD

**Issue by azureitte** [gdext/editor#26]
**Describe the bug**
In older levels (1.9, 1.8, etc.) dynamic colors (such as Player 1, Player 2 and Light BG) are not loaded proably and are being reset to default color (either Obj or Black).

**Steps to reproduce:**
1. Load an older level with dynamic colors (e.g. Hexagon Force) into GDExt
2. Save the level
3. Open it in GD
4. All the dynamic colors have been reset

**Expected behavior**
All colors are the same as they were before loading in GDExt

The reason behind this bug appears to be in `src/scripts/GDRenderW/data.json` - the default colors of some objects aren't specified correctly.

**Screenshots**
<img src="https://media.discordapp.net/attachments/779996545222311936/833689643211423834/unknown.png" />

This issue is being worked on at the moment and hopefully will be fixed soon

**Comment by azureitte** [comment]
Ok, here is the solution we came up with:
Dont change any color information of the object, even if there it doesnt exist. Another words, don't add a "default" color to an object, leave it as is

**Comment by iliasHDZ** [comment]
Fixed! (I hope so)
![image](https://user-images.githubusercontent.com/11091568/116136099-2c35d300-a6d2-11eb-8924-a0ebb3eecac9.png)

**Comment by azureitte** [comment]
yoo, awesome!
