### ISSUE TITLE
Helper scripts for building levels.

### ISSUE THREAD

**Issue by DexterHill0** [gdext/editor#53]
I thought a really useful feature for an external editor would be to allow the user to write scripts to automate tedious processes (like placing a load of objects). I've created a _really_ rough mockup of the feature.
The code written by the user is run using `eval`, which is usually a bad idea, but in this situation, since everything is running client side, I think it should be fine. There is alwas a library like [vm2](https://www.npmjs.com/package/vm2) in case it needed to be sandboxed. Because of `eval`, that means you can define variables like `blocks` which the user can reference in their code.
Once written, there are currently two buttons: one to execute the script and one to apply the changes. `execute` runs the code but it does not modify the level. `apply` is what actually makes the changes to the level.
There isn't any syntax highliting but something like [Prism](https://prismjs.com/) would work.

I just wanted to check is it ok if I continue working on this feature?

**Comment by iliasHDZ** [comment]
Sound good to me. However, I think that it's better you take @GDUcrash' advice.

**Comment by azureitte** [comment]
Hi and thanks for the suggestion!
Your idea sounds very similar to our "plugins system" (not out yet) which is planned for gdext v1.0. Basically, it allows developers to create custom plugins and macros to automate some tasks or enhance the editor and user experience

**Comment by DexterHill0** [comment]
Ah ok no worries. I was actually originally going to ask whether there was plugin support planned, so that's cool to hear. In that case, I'll wait until theyre released and develop it as a plugin instead.
