### ISSUE TITLE
cant open right side level editor toolbar

### ISSUE THREAD

**Issue by Ghdhdhdh** [gdext/editor#66]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows/MacOS/Web]
 - Version [e.g. 0.2]

**Additional context**

**Comment by naoei** [comment]
Please stop creating issues and then closing them afterwards without providing a reason as to why you closed them.

Also, as a side note, this project hasn't been worked on in a while (and might be abandoned, but with the nature of open source projects, anyone can continue working on this project).

**Comment by azureitte** [comment]
Correction: Please stop creating issues that are easy to solve by figuring out on your own or asking for help in Discord, i.e. "how do i move the camera" or "why does this not open". This section is meant for actual bugs with the software. Thank you

**Comment by naoei** [comment]
Maybe we should introduce some sort of instructions on how to use this software within the readme? Just to avoid situations like these in the future.
